nailedReact/bokgungom-market

my-app/src/pages/account/Login.jsx, package-lock.json
=> Feat: 로그인 마크업, 유효성 검사 #5

my-app/package-lock.json, my-app/package.json, my-app/src/pages/account/Register.jsx
=> Feat: 회원가입 마크업, 유효성 검사 #3

my-app/src/components/Button1.jsx
=> Refactor: 코드 리팩토링

my-app/src/components/userinput/Inp.jsx, my-app/src/components/userinput/UserInput.jsx, my-app/src/pages/account/Register.jsx, my-app/src/pages/splash/Splash.jsx
=> Feat/issue 34 사용자 인풋 컴포넌트 제작

my-app/src/components/shared/ConfirmModal/ConfirmModal.jsx, my-app/src/components/shared/ConfirmModal/confirmModal.style.js
=> Feat: 확인 모달창 마크업 #36

my-app/src/components/BlurInpWarn/BlurInpWarn.jsx, my-app/src/components/Warning.jsx, my-app/src/components/shared/Warning/Warning.jsx, my-app/src/pages/account/Register.jsx
-  Warning 컴포넌트를 사용하여 스타일을 공유할 수 있도록 함
=> Refactor/issue 39: 인풋 경고창 컴포넌트로 교체

my-app/src/pages/account/Login.jsx
- 로그인 유효성 검사 후 에러메시지 디스플레이
- 로그인 성공 시 로컬 스토리지에 토큰 저장
=> Feat: 로그인 유효성 검사 #47

my-app/src/pages/feed/UploadProduct.jsx
입력 완료 시 저장버튼 활성화
상품명 글자 수, 가격 원단위 자동 변환
공통 컴포넌트로 변경
=> 상품등록 페이지 마크업, API 구현#61

my-app/src/components/ProfileSetInpsTemp/ProfileSetInpsTemp.jsx, my-app/src/pages/account/EditProfileSignUp.jsx
리팩토링 전: 이미지 파일 서버 등록 요청을 파일이 바뀔 때 함
문제점: 사용자가 이미지 파일을 바꿔놓고 중간에 회원가입 안 하고 나갈 수 있는데, 서버에 불필요하게 이미지가 등록됨
해결: 이미지 파일 서버 등록 요청을 폼 제출시 할 수 있도록
=> Refactor: 회원가입시 프로필 설정 - 이미지 파일 서버 등록 요청을 폼 제출시로 변경 #66

my-app/src/components/ProfileSetInpsTemp/ProfileSetInpsTemp.jsx, my-app/src/pages/account/EditProfileSignUp.jsx
코드 수정 전: 이미지를 따로 등록하지 않을 경우 회원가입이 되지 않음
코드 수정 후: if를 이용해 이미지 등록이 안 돼도 회원가입이 되도록
=> Fix: 회원가입 시 프로필 설정 - 이미지 등록을 안 할 경우 회원가입이 안 되는 문제 해결 #72

my-app/src/components/NavBar/NavBar.jsx, my-app/src/pages/chat/ChatList.jsx, my-app/src/pages/chat/ChattingRoom.jsx, my-app/src/pages/chat/chat/ChatItem.jsx, my-app/src/pages/chat/chat/chatItem.style.js, my-app/src/pages/chat/chat/chatdata.json
챗 리스트 페이지 마크업 구현
챗 리스트 누를 경우 해당하는 페이지로 이동: 해당하는 페이지에 채팅 데이터 넘겨줌
NavBar import 경로 수정
=> Feat: 챗 리스트 페이지 마크업 #80

my-app/src/pages/profile/follow/FollowListCard.jsx, my-app/src/pages/profile/follow/Follower.jsx, my-app/src/pages/profile/follow/Following.jsx, my-app/src/pages/profile/userprofile/ProfileCard.jsx
=> feat: 팔로우, 언팔로우 기능 구현

my-app/public/index.html, my-app/src/components/Backdrop/Backdrop.jsx, my-app/src/components/Backdrop/backdrop.style.js, my-app/src/components/OptionModal/optionModal.style.js, my-app/src/components/TopBar.jsx, my-app/src/pages/chat/ChattingRoom.jsx, my-app/src/pages/chat/chat/ChatModal/ChatModal.jsx
- 모달 띄울 때 접근성 및 오류 방지 위해 리액트 포탈 이용: index.html에 모달을 띄울 곳을 정해놨습니다.
- 모달 외 클릭시 모달이 닫힐 수 있도록 Backdrop 컴포넌트를 하나 만들었습니다.
- 채팅방 나가기 클릭시 채팅 리스트 페이지로 이동합니다.
=> Feat/issue 111 개별 채팅방 모달창

my-app/src/components/PostCard.jsx, my-app/src/pages/profile/userprofile/Profile.jsx, my-app/src/pages/profile/userprofile/ProfileCard.jsx
=> Fix: 버그 수정

my-app/src/components/PostCard.jsx, my-app/src/components/TopBar.jsx, my-app/src/pages/feed/FeedFollower.jsx, my-app/src/pages/feed/FeedNoFollower.jsx, my-app/src/pages/feed/HomeFeed.jsx, my-app/src/pages/profile/userprofile/ProfileCard.jsx
- 홈피드 마크업, 스타일
- 팔로워가 없을 경우 FeedNoFollower로 넘어가서 검색하기 버튼 활성화 됨.
- 팔로워가 있는 경우 FeddFollower로 넘어가서 피드가 보여짐.
=> feat: 홈피드 기능구현, 마크업, 스타일링

my-app/src/pages/profile/follow/FollowListCard.jsx, my-app/src/pages/profile/follow/Follower.jsx, my-app/src/pages/profile/follow/Following.jsx, my-app/src/pages/profile/userprofile/ProfileCard.jsx
- 다른 사람 프로필 -> 팔로우 버튼기능 수정 필요
- 팔로잉 & 팔로워 리스트 화면에서 버튼 크기 수정 #123
=> Feat: 팔로잉 & 팔로워 계정에 맞게 나오도록 수정

my-app/src/components/PostAlbum.jsx, my-app/src/components/PostCard.jsx, my-app/src/components/PostList.jsx
게시물 앨범형으로 변경 기능 구현 
- PostAlbum 파일을 만들어서 이미지 파일만 따로 구현되도록함
- container을 gird로 앨범형으로 구현함
=> feat: 게시물 앨범형으로 변경 기능 구현

my-app/src/components/PostCard.jsx, my-app/src/components/PostList.jsx, my-app/src/pages/feed/FeedFollower.jsx, my-app/src/pages/feed/HomeFeed.jsx
=> Feat: 댓글 클릭시 해당 글의 상세 페이지로 이동 #131

my-app/src/pages/profile/userprofile/ProfileCard.jsx
api 요청하는 시간이 있어서 약간의 딜레이는 있는데 어느정도 잘 반영되는 것 같습니다!
=> Refactor: 팔로우/ 언팔로우할 때마다 팔로워 숫자 변경하여 렌더링 #145

my-app/src/components/TopBar.jsx, my-app/src/pages/feed/Search.jsx, my-app/src/pages/feed/SearchList.jsx
- button 컴포넌트에서 버튼을 없앴습니다.
- search 컴포넌트 내에서 count를 이용하여 검색기능이 되게 하였습니다.
=> feat: 검색기능 버튼없이 구현

my-app/src/components/Textarea/Textarea.jsx, my-app/src/pages/feed/UploadPost.jsx
- textarea 스타일 수정했습니다.
- 이미지 크기 수정
- 이미지 여러개 업로드는 계속 하다가 실패했습니다..
=> Fix: 포스트 등록 페이지 textarea 스타일, 이미지 크기 수정 #156

my-app/src/components/Button.jsx, my-app/src/components/InitialHeading/InitialHeading.jsx, my-app/src/components/ProfileImageSet/ProfileImageSet.jsx, my-app/src/components/ProfileSetInpsTemp/profileSetINpsTemp.style.js, my-app/src/components/userinput/Inp.jsx, my-app/src/components/userinput/UserInput.jsx, my-app/src/pages/account/EditProfileSignUp.jsx, my-app/src/pages/account/Login.jsx, my-app/src/pages/account/Register.jsx
로그인, 회원가입, 프로필 설정 페이지 스타일 수정했습니다.
웹 화면 가운데 정렬한 디자인도 봐주세요!
=> Style: 로그인, 회원가입, 프로필 설정 페이지 스타일 수정

my-app/src/pages/feed/Search copy.jsx, my-app/src/pages/feed/Search.jsx
=> fix: search 다른방식으로 기능변경

my-app/src/components/ConfirmModal/confirmModal.style.js, my-app/src/components/OptionModal/optionModal.style.js, my-app/src/pages/profile/userprofile/Profile.jsx
Feat: 프로필 페이지 모달창 #179
- TopBar 버튼 클릭시 모달창 띄움
- 설정 및 개인정보 클릭시 프로필 설정 페이지로
- 로그아웃
Style: 옵션 모달창 스타일 패딩 맞추기 #179
Style: 확인 모달창 컬러 테마 맞춤 #179
=> [Profile] 프로필 페이지 모달창

my-app/src/pages/profile/follow/EditProfile.jsx
=> Fix: 프로필 수정 페이지 로컬 스토리지 키 수정 #188

my-app/src/components/PostList.jsx, my-app/src/pages/profile/userprofile/ProfileCard.jsx, my-app/src/pages/profile/userprofile/SaledProductCard.jsx
- 수정 전: 로그인한 계정이 세민인 경우 => 수현님 프로필 들어간 후 => 하단 탐색 바에서 내 프로필 이동 클릭시 => 내 프로필이 뜨는게 아니라 수현님 프로필이 보이고 그걸 수정할 수 있게 돼있음
- 수정: useEffect에 의존성 배열로 username 추가
- forEach 대신 map 이용으로 변경
=> Fix: 하단 탐색 바 내 프로필 이동 클릭시 버그 #192

my-app/src/components/ImageUpload/ImageUpload.jsx, my-app/src/components/ImageUpload/imageUpload.style.js, my-app/src/pages/feed/PostEdit.jsx, my-app/src/pages/feed/UploadPost.jsx
Fix: input type file accept 파일 제한 #198
image/jpg, image/gif, image/png, image/jpeg, image/bmp, image/tif, image/heic
Style: 이미지 등록 아이콘 네브바 생길 때 더 위로 올림 #198
=> Bug/issue 198 - 이미지 허용 제한

my-app/src/components/CommentItem/CommentItem.jsx, my-app/src/pages/feed/PostDetail.jsx, my-app/src/pages/feed/feed/dateformat.js
- dateformat을 매번 호출하는 구조에서 문자중 시간만 추출해 +1해서 문자를 갈아끼우는 함수를 호출하는 거로 바꿈
=> Fix: 시간이 -1초부터 시작하는 문제 해결 #206

my-app/src/hook/useAuth1.js, my-app/src/pages/feed/PostDetail.jsx
- useAuth1 hook 안에 추가했습니다. useAuth랑 거의 비슷한데 useRef를 사용해서 일단 파일을 분리했습니다.
- 추후 useAuth와 useAuth1를 같이 합치는 리팩토링도 가능할 거 같습니다.
=> Fix: 프로필 상세 페이지 - 댓글 모달창 내가 쓴 댓글인거 인식 잘 못하는 문제 #203

my-app/src/components/TopBar.jsx, my-app/src/pages/account/Login.jsx, my-app/src/pages/account/Register.jsx, my-app/src/pages/account/loginRegister.style.js, my-app/src/pages/feed/UploadPost.jsx, my-app/src/pages/feed/UploadProduct.jsx
=> Feat/issue 208 글 작성 / 로그인 완료 시 페이지 이동

my-app/src/pages/feed/PostDetail.jsx
- 처음 조회 시 : 댓글 최신순 10개 불러옴
- 댓글 더보기 버튼 추가하여 클릭 시 더 많은 댓글 10개씩 더 불러옴
- 모든 댓글이 불러와졌을 때는 댓글 더보기 버튼 비활성화
=> Feat/issue 211 댓글 10개 이상 불러오기 

my-app/src/hook/useAuth1.js, my-app/src/pages/feed/PostDetail.jsx
=> Fix: 프로필 상세 페이지 - 댓글 모달창 내가 쓴거 제대로 인식 못하는 문제

my-app/src/pages/feed/PostDetail.jsx
pull request #214 #215 merge conflict 해결 과정에서 수현님 코드를 몇 개 지워서 잘 작동하지 않았던 문제를 해결했습니다
=> Fix: 병합 충돌 해결 #217

my-app/src/components/Toast.jsx, my-app/src/pages/feed/PostEdit.jsx, my-app/src/pages/feed/UploadPost.jsx, my-app/src/pages/feed/UploadProduct.jsx, my-app/src/pages/profile/follow/EditProfile.jsx, my-app/src/pages/splash/Splash.jsx
수정, 추가 구현 사항
- 피드 페이지처럼 스크롤이 생기는 페이지의 경우 토스트 메시지가 상단에 띄워져 스크롤을 올려야만 보인다.
- 게시물 삭제 시 토스트 메시지 띄우는 것 구현하지 못함
- 디자인 수정
=> Feat/issue 216 토스트 메시지 띄우기

my-app/src/pages/feed/HomeFeed.jsx, my-app/src/pages/feed/homeFeed.style.js, my-app/src/pages/profile/userprofile/SaledProductCard.jsx
=> feat: 페이지네이션

my-app/src/hook/usePostDetail.js, my-app/src/pages/feed/PostDetail.jsx
=> Feat/issue 212 - 게시글 상세 페이지 댓글 삭제 및 추가시 댓글 숫자 늘어남

my-app/src/pages/feed/UploadPost.jsx
이미지 없어도 업로드 가능하도록 수정하고 일부 코드 정리했습니다.
=> Refactor: 포스트 등록 페이지 코드 정리 및 이미지 없어도 업로드 되도록 수정

my-app/src/pages/feed/HomeFeed.jsx
=> style: 페이지네이션 스타일링

my-app/src/pages/feed/HomeFeed.jsx, my-app/src/pages/feed/homeFeed.style.js, my-app/src/pages/profile/follow/Follower.jsx, my-app/src/pages/profile/follow/Following.jsx
- 홈피드에서 페이지 수가 5보다 작을 경우 next, prev버튼 비활성화
-  팔로잉, 팔로워 리스트 수가 10개로 제한되지 않고 전부 나오도록 수정
=> 페이지네이션 수정, 팔로잉 팔로워 리스트 수정

my-app/public/manifest.json, my-app/src/components/Toast.jsx, my-app/src/hook/windowSize.js, my-app/src/pages/account/Register.jsx, my-app/src/pages/feed/UploadPost.jsx, my-app/src/pages/feed/UploadProduct.jsx, my-app/src/pages/splash/Splash.jsx
- 게시글 업로드 페이지에서 모바일 화면에서 내비바 없애기
- 상품 업로드 페이지에서 모바일 화면에서 내비바 없애기
- 기타 수정 사항
- 기본 프로필 사진 border 제거
-  fowardRef 오류 수정
- 스플래시 화면에서 로그인 되어있다면 바로 피드로 이동
- manifest.json 오류 수정
=> Issue 231 반응형 내비바 없애기

my-app/src/components/PostList.jsx, my-app/src/components/userinput/UserInput.jsx, my-app/src/pages/account/EditProfileSignUp.jsx, my-app/src/pages/account/Register.jsx, my-app/src/pages/feed/PostEdit.jsx, my-app/src/pages/feed/UploadPost.jsx, my-app/src/pages/profile/follow/FollowListCard.jsx, my-app/src/pages/profile/follow/Follower.jsx, my-app/src/pages/profile/follow/Following.jsx, my-app/src/pages/profile/userprofile/Profile.jsx
=> Fix: Netlify 빌드 오류 수정 #241

my-app/src/pages/feed/UploadPost.jsx, my-app/src/pages/feed/UploadProduct.jsx
- 상품 업로드 페이지
- 게시글 업로드 페이지
아까  충돌 수정하면서 제가 잘못 수정한게 있는 것 같아서 다시 수정했습니다!!!
=> Fix: 내비게이션 바 반응형 오류 수정

my-app/src/components/Backdrop/backdrop.style.js
=> Style: 모달창 백드롭 topbar 덮지 못하는 이슈 해결 #249

my-app/src/pages/feed/UploadPost.jsx
- 게시글 입력되면 버튼 활성화
- 게시글 없이 저장 버튼 클릭하면 alert
- 게시글 업로드 완료 후 본인 프로필 페이지로 이동
=> Fix: 저장 버튼 활성화 및 저장 완료 후 프로필 페이지로 이동 #252

my-app/src/pages/feed/PostEdit.jsx, my-app/src/pages/feed/UploadPost.jsx
특이사항: 게시물 업로드 페이지에서 이미지만 등록시에도 글 작성이 가능하도록 함
=> Fix: 게시물 업로드/수정 페이지 버튼 활성화 제대로 안 되는 문제 #257

my-app/src/components/NavBar/navBar.style.js
- div > ul > li > a 구조에서 nav > ul > li > a로
=> Refactor: NavBar HTML 마크업 리팩토링 #255

my-app/public/index.html, my-app/src/components/Toast.jsx, my-app/src/components/TopBar.jsx, my-app/src/components/userinput/UserInput.jsx, my-app/src/pages/feed/UploadPost.jsx, my-app/src/pages/profile/follow/Follower.jsx, my-app/src/pages/profile/follow/Following.jsx, my-app/src/pages/profile/follow/followFollowing.style.js, my-app/src/pages/profile/userprofile/ProfileCard.jsx
- 모바일 일때 팔로잉 & 팔로워 목록 하단 마진
- 모바일 검색창 placeholder가 보이지 않음
-  모바일 상품 업로드 상단 패딩 줄이기
-  프로필 이미지 border-radius
-  토스트 메시지 위치
=> Issue 254 모바일 버전 스타일링 이슈

my-app/src/pages/profile/userprofile/SaledProductCard.jsx
- 이미지 찌그러짐 object-fit contain으로 해결
- 글씨 색 테마에 안 맞음
=> Style: 판매중인 상품 스타일 CSS 수정 #266

my-app/src/components/PostCard.jsx, my-app/src/pages/feed/PostDetail.jsx
- 2장일 경우에만 Cont를 하나 추가하여 scroll로 스타일링 함.
=> style: 게시물 이미지가 2장 이상일 경우 스크롤 스타일링

my-app/src/components/ConfirmModal/confirmModal.style.js, my-app/src/components/OptionModal/optionModal.style.js
=> Issue 276 모달 호버 애니메이션 추가

my-app/public/index.html, my-app/public/manifest.json
모바일 기기에서 입력창에 포커싱될 때 화면 전체가 확대되는 문제가 있었음
index.html 의 head에서
```<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no, maximum-scale=1" />```
meta 태그를 다음과 같이 설정해줌으로써 해결
=> Bug/issue 278 모바일 입력창 확대 효과 제거 및 사이트 설정 변경

my-app/package-lock.json, my-app/package.json, my-app/src/components/PostAlbum.jsx, my-app/src/components/PostList.jsx, my-app/src/pages/profile/userprofile/ProfileCard.jsx
=> 무한스크롤, 앨범형 아이콘 수정

my-app/src/components/CommentItem/CommentItem.jsx, my-app/src/components/PostCard.jsx, my-app/src/components/ProfileImageSet/ProfileImageSet.jsx, my-app/src/components/postEditUserProfile.style.js, my-app/src/pages/chat/chat/ChatItem/ChatItem.jsx, my-app/src/pages/chat/chat/Incoming/incoming.style.js, my-app/src/pages/feed/PostDetail.jsx, my-app/src/pages/profile/follow/FollowListCard.jsx
- 게시물 작성하는 곳 프로필 사진 보더
- 프로필 사진 변경하는 곳 프로필 사진 보더
- 채팅창 안에서 프로필 사진 보더
- 댓글 작성하는 곳 프로필 사진 보더
- 댓글 프로필 사진 보더
=> Style: 프로필 사진 영역 통일#281

my-app/public/index.html, my-app/src/app.style.js
정적 폴더에 있는 index.html 에 import하여 폰트 적용 완료
=> Fix: 폰트 import 위치 변경 #290

my-app/src/hook/usePostDetail.js, my-app/src/pages/feed/PostDetail.jsx
- 본인 게시물일 경우 수정 및 삭제
- 본인 게시물이 아닐 경우 신고
- 토스트 메시지 + 삭제 후 이전 페이지 이동
- 한계점: 모달창 부분 코드가 너무 길고 비슷비슷한 useState 반복, 토스트 메시지 #271 이슈 해결 안 한 상태
=> Feat: 게시물 상세 페이지 모달창 #284

my-app/src/components/PostCard.jsx, my-app/src/pages/feed/PostDetail.jsx, my-app/src/pages/feed/PostEdit.jsx, my-app/src/pages/feed/UploadPost.jsx, my-app/src/pages/feed/UploadProduct.jsx, my-app/src/pages/profile/follow/EditProfile.jsx
- 모달창 띄웠다 사라지는 시간과 페이지 이동 대기 시간 일치 시킴
=> Fix: 모달창 콘솔 에러 해결 #297

my-app/package-lock.json, my-app/package.json, my-app/src/components/PostCard.jsx, my-app/src/components/PostList.jsx
=> fix: key값 오류 수정

my-app/src/components/PostAlbum.jsx
=> Style: 프로필 페이지 이미지 앨범보기 수정 #317

my-app/src/pages/feed/UploadPost.jsx
포스트 등록 이미지 업로드 버튼 - 모바일 화면에서 위치 수정
=> Fix: 이미지 업로드 버튼 위치 수정

my-app/src/components/ImageUpload/imageUpload.style.js, my-app/src/components/ProductImageSet/productImageSet.style.js, my-app/src/components/Textarea/Textarea.jsx, my-app/src/pages/feed/PostEdit.jsx
이슈: 게시물 수정시 원래 데이터를 가져와서 textarea의 높이를 늘려줘야 하는데, 이를 구현하고자 코드를 짰지만 높이 수정이 정확하지 않습니다.
참고 사이트: https://bydawn25.tistory.com/44
=> Style: 게시물 작성/수정 여러장 이미지 업로드시 사진 정렬 맞춤 #325

my-app/src/components/Button.jsx, my-app/src/components/PostList.jsx, my-app/src/pages/profile/follow/FollowListCard.jsx, my-app/src/pages/profile/userprofile/ProfileCard.jsx
=> Issue 331 스타일링 수정

my-app/src/components/ImageUpload/imageUpload.style.js, my-app/src/pages/feed/UploadProduct.jsx
=> Style: 상품 업로드 페이지 이미지 업로드 아이콘 위치 수정 #339

my-app/src/components/PostAlbum.jsx, my-app/src/pages/feed/HomeFeed.jsx, my-app/src/pages/feed/homeFeed.style.js
=> Bug/issue 344 페이지네이션 스타일 수정

my-app/src/components/PostCard.jsx, my-app/src/components/PostList.jsx
- 프로필 페이지에서 postcard more 버튼 클릭 후 삭제 클릭시 다른 페이지로 넘어감 해결
- 프로필 페이지에서 게시글 모두 삭제시 "게시물이 없습니다" 뜨도록
- 한줄로 길게 입력시 줄바꿈 일어나지 않는 문제 & 줄바꿈 적용 안 되는 문제 해결
=> Bug/issue 346 - 포스트카드 관련 버그 해결

my-app/src/components/PostList.jsx, my-app/src/pages/profile/userprofile/Profile.jsx
- useEffect와 useCallback 의존성 배열에 username 추가
=> Fix: 다른 사람 페이지 후 내 프로필 페이지 들어가면 포스트리스트 재렌더링이 안 되는 문제 해결 #348

my-app/src/app.style.js, my-app/src/pages/feed/homeFeed.style.js
=> Style: 모바일 페이지네이션 폰트 오류 수정 #344

my-app/src/pages/account/EditProfileSignUp.jsx
- 페이지 이동으로 로컬 스토리지에 토큰이 저장되지 않는 문제 발생
- setTimeOut으로 토큰 저장 완료 후 페이지 이동
=> Fix: 회원가입 오류 수정

my-app/src/pages/feed/PostDetail.jsx
- 문제 원인: userIdRef가 어떨 때 undefined로 잡히면서 같지 않기 때문에 계속 댓글 신고하기 모달창만 떴음
- 해결 방법: userIdRef를 useState 대신 useRef로 함(딜레이 방지를 위해)
- 한계점: 왜 어떨 때 userIdRef가 undefined로 잡히는지 파악하지 못함. 확인 요망
=> Fix: 댓글 신고/삭제 정확하지 않은 문제 #351

README.md
- 미리보기 이미지에 깃허브 위키 링크 연결
- 프로젝트 소개 추가
- 모듈 설명  추가
=> Docs: README 수정

my-app/src/pages/feed/HomeFeed.jsx, my-app/src/pages/feed/homeFeed.style.js
모바일상에서는 onfocus, onblur을 통한 뒷 배경 변경이 되지 않아 onclick으로만 가능하도록 수정함.
=> Bug/issue 344 모바일 상에서 onfocus, onblur 불가능

my-app/src/components/PostAlbum.jsx, my-app/src/components/PostCard.jsx
fix: 앨범형에서 업로드 오류 있는 이미지 수정
onerror로 업로드가 되면 이미지 없다는 다른 이미지로 수정됨.
=> fix: 앨범형에서 업로드 오류 있는 이미지 수정

my-app/src/pages/feed/UploadProduct.jsx, my-app/src/pages/profile/userprofile/SaledProductCard.jsx
상품 등록 페이지 & 프로필 판매 중인 상품
- 가격 숫자 세 번째 자리마다 콤마 표시
=> Fix: 가격 숫자 세 번째 자리마다 콤마 표시 #364

my-app/src/components/PostList.jsx, my-app/src/pages/feed/HomeFeed.jsx, my-app/src/pages/profile/userprofile/SaledProductCard.jsx
페이지네이션 1번 스타일링, 판매중인 상품 없을시 이미지 수정
=> 페이지네이션 1번 스타일링, 판매중인 상품 없을시 이미지 수정

my-app/src/components/CommentItem/CommentItem.jsx, my-app/src/components/PostCard.jsx, my-app/src/components/PostList.jsx, my-app/src/pages/feed/HomeFeed.jsx, my-app/src/pages/profile/follow/Follower.jsx, my-app/src/pages/profile/follow/Following.jsx
fix: 프로필사진 기본이미지로 수정, 페이지네이션 수정, 팔로워 팔로잉 리스트에서 본인은 제외
=> fix: 프로필사진 기본이미지로 수정, 페이지네이션 수정, 팔로워 팔로잉 리스트에서 본인은 제외

my-app/src/pages/feed/PostEdit.jsx, my-app/src/pages/feed/UploadPost.jsx
한계점: 텍스트에리어 길어질 경우 위치 이상한 거 아직 해결 못함
=> Fix: 프로필 이미지 아이콘 포커스 상태로 리사이즈 경우 데스크탑에서 bottom 50% 문제 해결 #338

my-app/src/pages/profile/userprofile/ProfileCard.jsx
=> Feat: 공유하기 기본 기능 추가 #370

my-app/src/components/postView/PostCard.jsx, my-app/src/pages/profile/userprofile/ProfileCard.jsx, my-app/src/pages/profile/userprofile/SaledProductCard.jsx
saledProductCard.jsx, profileCard.jsx, postCard.jsx
3개 파일에서 이미지 alt 값 추가함
=> Refactor: 이미지 alt 값 추가 #381

my-app/public/index.html
`user-scalable` 속성을  `no`에서  `yes`로 변경함
사용자가 브라우저의 확대축소를 가능하게 할 것인지에 관한 속성
=> Fix: user-scalable 값 yes로 변경 #388

my-app/public/index.html
=> Fix: maximim-scale 제한하지 않음 #388

my-app/src/pages/chat/ChatList.jsx, my-app/src/pages/chat/chatList.style.js, my-app/src/pages/chat/chatListRoom.style.js
* 문제 상황: 데스크탑 버전에서 개별 채팅방 왼쪽에 여백이 생김
* 이유: 채팅리스트 페이지와 개별 채팅방에서 공통적인 스타일드 컴포넌트 사용하기 때문
* 해결: 각 페이지에서 사용하는 스타일드 컴포넌트 구분
=> Fix: 개별 채팅방 데스크탑 스타일 문제 #405
